version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    time: "16:00"
    timezone: Etc/Universal
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.code.gson:gson
    versions:
    - "> 2.2.4"
  - dependency-name: com.google.guava:guava
    versions:
    - "> 17.0"
  - dependency-name: org.apache.maven.plugins:maven-shade-plugin
    versions:
    - "> 3.2.3, < 3.3"
  - dependency-name: pl.project13.maven:git-commit-id-plugin
    versions:
    - "> 4.0.0, < 4.1"
  - dependency-name: com.zaxxer:HikariCP
    versions:
    - 4.0.0
    - 4.0.1
    - 4.0.2
  - dependency-name: net.md-5:bungeecord-config
    versions:
    - 1.16-R0.4
